import { createSlice } from "@reduxjs/toolkit"; // state slice

const initialState = {
    movies:{},
};

/* a reducer is a pure function that takes an action and the previous state of the application and returns the new state. 
The action describes what happened and it is the reducer's job to return the new state based on that action. */
const movieSlice = createSlice({
    name:'movies',
    initialState,
    reducers:{
        addMovies: ( state, {payload} ) => {
            state.movies = payload; 
        }
    },
});

// export action creator generated by adding a movie
export const { addMovies } = movieSlice.actions;
// export reducer
export default movieSlice.reducer; 
// fetch value from the store
export const getAllMovies = (state) => state.movies.movies
